// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDYKbU4WB5-sQlBBAkcD4jDMfWIlSHzzo',
    appId: '1:567131096056:web:36a9fad1d913b34b95cc0d',
    messagingSenderId: '567131096056',
    projectId: 'chat-app-f22a5',
    authDomain: 'chat-app-f22a5.firebaseapp.com',
    storageBucket: 'chat-app-f22a5.firebasestorage.app',
    measurementId: 'G-VBWF3WG8LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwRbuqCejbUR7PjbyO76j8TswuzuCYlGw',
    appId: '1:547553859687:android:907c7827549fc8b4a95cc2',
    messagingSenderId: '547553859687',
    projectId: 'evently-app-46c2d',
    storageBucket: 'evently-app-46c2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApiw2mO71x2vsfSN5vjPwAY0YGkhFaK4g',
    appId: '1:547553859687:ios:260c9ff157d38302a95cc2',
    messagingSenderId: '547553859687',
    projectId: 'evently-app-46c2d',
    storageBucket: 'evently-app-46c2d.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJcEZivCHlqO7LkbAmwaO9_uJZi0CDTkU',
    appId: '1:567131096056:ios:703a3a7cf26e9bf595cc0d',
    messagingSenderId: '567131096056',
    projectId: 'chat-app-f22a5',
    storageBucket: 'chat-app-f22a5.firebasestorage.app',
    iosClientId:
        '567131096056-46btakd9p8mdmgmumgiv70tpfnstsh1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi-MJpeItT7JOT3vFxIZe5Pq24dYAp2V0',
    appId: '1:567131096056:web:0184eb656d4c011995cc0d',
    messagingSenderId: '567131096056',
    projectId: 'chat-app-f22a5',
    authDomain: 'chat-app-f22a5.firebaseapp.com',
    storageBucket: 'chat-app-f22a5.firebasestorage.app',
    measurementId: 'G-M3X74SWR7V',
  );
}